language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - "node_modules"
install:
    - "npm install"
    - "gulp tslint"
    - "gulp test"
script: "npm run coverage"
after_script: "npm install coveralls@3.0.0 && cat ./coverage/lcov.info | coveralls"
